### PR TITLE
Use Iconv to convert UTF-8 charactors

### PR DESCRIPTION
**Pull request by DavidBeale**
Add conversion of UTF-8 form data to PDF compatible UTF-16.

This fixes issues with chars such as "£" which would previously appear as "Â£" in the PDF.

### CODE REVIEW

**Comment by westy92** [comment]
You should look into figuring out what was wrong before I removed this code: https://github.com/dommmel/fill-pdf/pull/22/files and try to revert it.

Maybe I just didn't have a proper test case.  Either way, use `iconv-lite` instead of `iconv`.

**Comment by DavidBeale** [comment]
I had a play with iconv-lite, and I can't get it to work.

**Comment by ScottONeal** [comment]
It would be nice if we can opt out of iconv as much as possible with this module. I would almost be more inclined to create a middleware layer where one could put their on alterations in, instead of adding iconv back.

I'd be welcome to a PR that includes a middleware system, which you can then utilize to fit your needs.

Unless there is an overwhelming desire to reintegrate iconv

**Comment by ScottONeal** [comment]
Closing due to no activity. Can reopen if needed.

**Pull request closed without merging**
