### PR TITLE
make isAbsolute compatible with older node ver.

### LINKED ISSUE #12: issue with absolute path
I had an issue when passing an absolute path to the `generatePdf` function. My path looked something like this `/srv/www/api/services/../../assets/template.pdf` because this path is generated dynamically using `__dirname` , I temp. fixed this issue by removing `__dirname` from the `generatePdf` in https://github.com/dommmel/fill-pdf/blob/master/index.js#L60 , but I didn't raise a pull request because I didn't test it thoroughly.

HINT: I can't use relative paths, because `fill-pdf` module is installed locally in a different folder than where it is installed on my production env. but my api code / folder structure is the same, that's why am forming the path to the .pdf template from the service.

### PR DESCRIPTION
**Pull request by wassimsalib**
based on this discussion here: 
http://stackoverflow.com/questions/21698906/how-to-check-if-a-path-is-absolute-or-relative

I think this solution will help fix #12 and make it backward compatible to older node versions.

### CODE REVIEW

**Comment by ScottONeal** [comment]
Thanks for the PR! 

If possible can you sink the function down to the bottom of the file and name the argument 'p' to something a little more informative?

Thanks! :+1:

**Comment by wassimsalib** [comment]
I moved the function to the end, but I guess you don't want it to be exposed externally, so I didn't add it to exports. also I renamed `p` parameter to `Path` hopefully it won't be confusing with the `path` API

**Comment by muhammadghazali** [comment]
Or you guys can try out this package:
https://www.npmjs.com/package/path-is-absolute

**Comment by ScottONeal** [comment]
Looks good, thanks! Will look into using path-is-absolute down the road.

:beers:

**Comment by ScottONeal** [comment]
Published new version 0.1.3 to NPM

**Comment by wassimsalib** [comment]
Thanks! :beers:

**Pull request merged**
